# Generated by Django 3.2.19 on 2023-07-15 13:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('E_Library', '0023_auto_20230714_0500'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='book_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Published', 'Published')], default='Pending', max_length=9),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_type',
            field=models.CharField(choices=[('A', 'Admin'), ('M', 'Moderator'), ('U', 'User')], default='U', max_length=1),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('answer_photo', models.ImageField(blank=True, null=True, upload_to='answer/photos')),
                ('answer_video', models.FileField(blank=True, null=True, upload_to='answer/videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.mp4', '.webm', '.ogg'])])),
                ('question_status', models.CharField(choices=[('Answered', 'Answered'), ('Unanswered', 'Unanswered'), ('Rejected', 'Rejected')], default='Answered', max_length=10)),
                ('question_type', models.CharField(choices=[('Public', 'Public'), ('Private', 'Answered')], default='Private', max_length=7)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='E_Library.questioncategory')),
            ],
        ),
    ]
