# Generated by Django 3.2.19 on 2023-07-15 13:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Library', '0026_auto_20230715_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Published', 'Published')], default='Pending', max_length=9),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_video',
            field=models.FileField(blank=True, null=True, upload_to='answer/videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg'])]),
        ),
    ]
