# Generated by Django 3.2.19 on 2023-07-17 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('E_Library', '0034_auto_20230717_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_status',
            field=models.CharField(choices=[('Published', 'Published'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=9),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_status',
            field=models.CharField(choices=[('Unanswered', 'Unanswered'), ('Answered', 'Answered'), ('Rejected', 'Rejected')], default='Unanswered', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Private', max_length=7),
        ),
        migrations.AlterField(
            model_name='rank',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='E_Library.question'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_type',
            field=models.CharField(choices=[('M', 'Moderator'), ('U', 'User'), ('A', 'Admin')], default='U', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='rank',
            unique_together={('user', 'question')},
        ),
    ]
