# Generated by Django 3.2.19 on 2023-07-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Library', '0038_auto_20230721_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_status',
            field=models.CharField(choices=[('Published', 'Published'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=9),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_status',
            field=models.CharField(choices=[('Answered', 'Answered'), ('Unanswered', 'Unanswered'), ('Rejected', 'Rejected')], default='Unanswered', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Private', max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_type',
            field=models.CharField(choices=[('M', 'Moderator'), ('A', 'Admin'), ('U', 'User')], default='U', max_length=1),
        ),
    ]
