# Generated by Django 3.2.19 on 2023-07-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Library', '0039_auto_20230721_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Published', 'Published')], default='Pending', max_length=9),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Answered', 'Answered'), ('Unanswered', 'Unanswered')], default='Unanswered', max_length=10),
        ),
    ]
